name: Execute Test Cases
run-name: Executing Unit Tests
on: 
  push:
    branches:
      - master
jobs:
  Execute-Springboot-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'
          architecture: x64
      - name: Executing mvn tests
        run: mvn test -Dspring.profiles.active=test
